before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    main: ./cmd/csi-vultr-driver/
    
    env:
      - CGO_ENABLED=0

    binary: csi-vultr-plugin
    
    flags:
      - -trimpath #removes all file system paths from the compiled executable

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}_v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "vultr/vultr-csi:latest"
      - "vultr/vultr-csi:{{ .Tag }}"

release:
  github:
    owner: Vultr
    name: vultr-csi