####################
### Storage Classes
####################
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: block.csi.vultr.com
spec:
  attachRequired: true
  podInfoOnMount: true

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  storage_type: "block"
  disk_type: "nvme"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-retain
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storage_type: "block"
  disk_type: "nvme"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-hdd
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  storage_type: "block"
  disk_type: "hdd"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-hdd-retain
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storage_type: "block"
  disk_type: "hdd"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-vfs-storage
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  storage_type: "vfs"
  disk_type: "nvme"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-vfs-storage-retain
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storage_type: "vfs"
  disk_type: "nvme"

#########################
### Volume Snapshot Classes
#########################
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: vultr-block-storage
driver: block.csi.vultr.com
deletionPolicy: Delete

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: vultr-block-storage-retain
driver: block.csi.vultr.com
deletionPolicy: Retain

###################
### CSI Controller
###################
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-vultr-controller
  namespace: kube-system
spec:
  serviceName: "csi-vultr"
  replicas: 1
  selector:
    matchLabels:
      app: csi-vultr-controller
  template:
    metadata:
      labels:
        app: csi-vultr-controller
        role: csi-vultr
    spec:
      serviceAccountName: csi-vultr-controller-sa
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.4.0
          args:
            - "--volume-name-prefix=pvc"
            - "--volume-name-uuid-length=16"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=90s"
            - "--v=5"
            - "--default-fstype=ext4"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.7.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=30s"
            - "--v=5"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
            - "--timeout=90s"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-vultr-plugin
          image: vultr/vultr-csi:v0.19.0
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(VULTR_API_KEY)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: VULTR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: vultr-csi
                  key: api-key
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: { }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-vultr-controller-sa
  namespace: kube-system

## Attacher Role + Binding
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-attacher-role
rules:
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "volumeattachments" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "volumeattachments/status" ]
    verbs: [ "patch" ]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-attacher-binding
subjects:
  - kind: ServiceAccount
    name: csi-vultr-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vultr-attacher-role
  apiGroup: rbac.authorization.k8s.io

## Provisioner Role + Binding
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-provisioner-role
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "list", "watch", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "volumeattachments" ]
    verbs: [ "get", "list", "watch" ]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: csi-vultr-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vultr-provisioner-role
  apiGroup: rbac.authorization.k8s.io

## Snapshotter Role + Binding
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-snapshotter-role
rules:
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "list", "watch", "create", "update", "patch" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotcontents" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotcontents/status" ]
    verbs: [ "update", "patch" ]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: csi-vultr-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vultr-snapshotter-role
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-snapshotter-leaderelection
  namespace: kube-system
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "watch", "list", "delete", "update", "create" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-snapshotter-leaderelection
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: csi-vultr-controller-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: csi-vultr-snapshotter-leaderelection
  apiGroup: rbac.authorization.k8s.io


############
## CSI Node
############
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-vultr-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-vultr-node
  template:
    metadata:
      labels:
        app: csi-vultr-node
        role: csi-vultr
    spec:
      serviceAccountName: csi-vultr-node-sa
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/block.csi.vultr.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
        - name: csi-vultr-plugin
          image: vultr/vultr-csi:v0.19.0
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
            capabilities:
              add: [ "SYS_ADMIN" ]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: device-dir
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/block.csi.vultr.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        - name: udev-rules-etc
          hostPath:
            path: /etc/udev
            type: Directory
        - name: udev-rules-lib
          hostPath:
            path: /lib/udev
            type: Directory
        - name: udev-socket
          hostPath:
            path: /run/udev
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-vultr-node-sa
  namespace: kube-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: csi-vultr-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vultr-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-node-driver-registrar-role
rules:
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch" ]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-resizer-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vultr-resizer-binding
subjects:
  - kind: ServiceAccount
    name: csi-vultr-controller-sa
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-vultr-resizer-role
