kind: Pod
apiVersion: v1
metadata:
  name: readme-app
spec:
  containers:
    - name: readme-app
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: vultr-volume-1
        - mountPath: "/data-2"
          name: vultr-volume-2
      command: [ "sleep", "1000000" ]
  volumes:
    - name: vultr-volume-1
      persistentVolumeClaim:
        claimName: csi-pvc-1
    - name: vultr-volume-2
      persistentVolumeClaim:
        claimName: csi-pvc-2